exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=yaml]
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: git://github.com/elidupuis/mirrors-sass-lint
    sha: '5cc4565'
    hooks:
      - id: sass-lint
